name: manual work
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install soft
        run: |
          (echo 'deb http://pkg.cloudflare.com/ focal main' | sudo tee /etc/apt/sources.list.d/cloudflare-main.list )
          (curl -C - https://pkg.cloudflare.com/pubkey.gpg | sudo apt-key add -)
          sudo apt-get update
          sudo apt-get install -y cloudflared 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
